// Generated by gencpp from file test_the_launch/Num.msg
// DO NOT EDIT!


#ifndef TEST_THE_LAUNCH_MESSAGE_NUM_H
#define TEST_THE_LAUNCH_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_the_launch
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : mun(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : mun(0)  {
  (void)_alloc;
    }



   typedef int64_t _mun_type;
  _mun_type mun;





  typedef boost::shared_ptr< ::test_the_launch::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_the_launch::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::test_the_launch::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::test_the_launch::Num > NumPtr;
typedef boost::shared_ptr< ::test_the_launch::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_the_launch::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_the_launch::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_the_launch

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'test_the_launch': ['/home/wenjun/XinXinboy/FWforU/Work/src/test_the_launch/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_the_launch::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_the_launch::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_the_launch::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_the_launch::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_the_launch::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_the_launch::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_the_launch::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24a51b5281936e58f18138cdb36963e4";
  }

  static const char* value(const ::test_the_launch::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24a51b5281936e58ULL;
  static const uint64_t static_value2 = 0xf18138cdb36963e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_the_launch::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_the_launch/Num";
  }

  static const char* value(const ::test_the_launch::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_the_launch::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 mun\n\
";
  }

  static const char* value(const ::test_the_launch::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_the_launch::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mun);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_the_launch::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_the_launch::Num_<ContainerAllocator>& v)
  {
    s << indent << "mun: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mun);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_THE_LAUNCH_MESSAGE_NUM_H
