// Generated by gencpp from file beginner_tutorials/AddTwoInts2.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ADDTWOINTS2_H
#define BEGINNER_TUTORIALS_MESSAGE_ADDTWOINTS2_H

#include <ros/service_traits.h>


#include <beginner_tutorials/AddTwoInts2Request.h>
#include <beginner_tutorials/AddTwoInts2Response.h>


namespace beginner_tutorials
{

struct AddTwoInts2
{

typedef AddTwoInts2Request Request;
typedef AddTwoInts2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts2
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::AddTwoInts2 > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::beginner_tutorials::AddTwoInts2&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::AddTwoInts2 > {
  static const char* value()
  {
    return "beginner_tutorials/AddTwoInts2";
  }

  static const char* value(const ::beginner_tutorials::AddTwoInts2&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::AddTwoInts2Request> should match 
// service_traits::MD5Sum< ::beginner_tutorials::AddTwoInts2 > 
template<>
struct MD5Sum< ::beginner_tutorials::AddTwoInts2Request>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::AddTwoInts2 >::value();
  }
  static const char* value(const ::beginner_tutorials::AddTwoInts2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::AddTwoInts2Request> should match 
// service_traits::DataType< ::beginner_tutorials::AddTwoInts2 > 
template<>
struct DataType< ::beginner_tutorials::AddTwoInts2Request>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::AddTwoInts2 >::value();
  }
  static const char* value(const ::beginner_tutorials::AddTwoInts2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::AddTwoInts2Response> should match 
// service_traits::MD5Sum< ::beginner_tutorials::AddTwoInts2 > 
template<>
struct MD5Sum< ::beginner_tutorials::AddTwoInts2Response>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::AddTwoInts2 >::value();
  }
  static const char* value(const ::beginner_tutorials::AddTwoInts2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::AddTwoInts2Response> should match 
// service_traits::DataType< ::beginner_tutorials::AddTwoInts2 > 
template<>
struct DataType< ::beginner_tutorials::AddTwoInts2Response>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::AddTwoInts2 >::value();
  }
  static const char* value(const ::beginner_tutorials::AddTwoInts2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ADDTWOINTS2_H
